### ISSUE TITLE
Ch2Ex1 is broken

### ISSUE THREAD

**Issue by richierocks** [machow/courses-pton-shell#1]
@machow this exercise times out

https://campus.datacamp.com/courses/introduction-to-the-shell-at-princeton-public-library/working-with-file-contents?ex=1

I don't have permission to edit on Teach, to tricky to tell why.

**Comment by machow** [comment]
@richierocks this was for a class at the princeton public library. I wonder if I used the wrong flag to make it public to them? Feel free to take any necessary steps to resolve. Closing here, since for the purposes of the course, it was okay for an exercise to time out (shell times out if the solution ends in a prompt)

(see https://datacamp.slack.com/archives/C5AFBR69M/p1533739370000042)
